# Generated by Django 3.2.7 on 2021-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0002_todo_assign_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='Position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Monitor', 'Monitor'), ('Worker', 'Worker')], default='Wk', max_length=15),
        ),
    ]
