# Generated by Django 3.2.7 on 2021-10-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0005_auto_20211001_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='user',
            new_name='id',
        ),
    ]
