# Generated by Django 3.2.7 on 2021-10-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0006_rename_user_userreg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='id',
            new_name='Id',
        ),
    ]
