# Generated by Django 3.2.7 on 2021-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0007_rename_id_userreg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Assign',
            field=models.ManyToManyField(to='managementapp.UserReg'),
        ),
    ]
